import fs from "node:fs";
import path from "node:path";
import { parse, applyEdits, modify, FormattingOptions } from "jsonc-parser";

export type SliceItem = { kind: "file" | "dir"; path: string };
export type SliceDef = {
  id: string;
  name: string;
  channel: string;
  items: SliceItem[];
};

export type Manifest = {
  settings: {
  contextFile: string;
  ignore: string[];
  dirInclude?: string[];
  dirExclude?: string[];
  tokenWarn?: {
  modelMaxTokens?: number;
  warnAt?: number; // 0..1 (e.g. 0.85)
  };
  tree?:
    | {
        roots?: string[];
        maxDepth?: number;
        maxEntries?: number;
        mode?: "dirs-only" | "dirs-and-files";
      }
    | undefined;
};
  slices: SliceDef[];
};

const FORMAT: FormattingOptions = { insertSpaces: true, tabSize: 2, eol: "\n" };

export const DEFAULT_MANIFEST_FILE = "slice.jsonc";

export function manifestPath(cwd = process.cwd(), filename = DEFAULT_MANIFEST_FILE) {
  return path.join(cwd, filename);
}

export function initTemplate(): string {
  // Note: JSONC with comments. Keep it human-editable.
    return `{
  // Global settings for Sliceza.
  // This file is safe to edit by hand.
  // Comments and formatting will be preserved.
  "settings": {
    // The file generated by \`sliceza build\`
    "contextFile": "slice_context.md",

    // Common generated / metadata paths are ignored by default.
    // Add paths or glob patterns sliceza should ignore here
    "ignore": ["node_modules/**", "dist/**", ".git/**"],

    // File filters applied when expanding directories.
    // These are glob-lite (extension + substring based).
    "dirInclude": ["**/*.ts", "**/*.html", "**/*.css", "**/*.scss", "**/*.md"],
    "dirExclude": ["**/*.map", "**/*.min.*"],

    // Optional: token warning (estimate) for slice_context.md.
    // This is an approximation; actual truncation depends on your model/tool.
    "tokenWarn": { "modelMaxTokens": 128000, "warnAt": 0.85 },

    // Optional: generate a context tree from specific roots.
    // mode: "dirs-only" is more token-efficient than "dirs-and-files".
    // Example:
    // "tree": { "roots": ["src"], "mode": "dirs-only", "maxDepth": 6, "maxEntries": 500 }
    "tree": { "roots": [], "mode": "dirs-only", "maxDepth": 6, "maxEntries": 500 }
  },

  // Slices are named groups of files.
  // Each slice belongs to a "channel" (a simple tag, often a color).
  "slices": []
}
`;
}

export function ensureManifest(cwd = process.cwd()): { file: string; created: boolean } {
  const file = manifestPath(cwd);
  if (!fs.existsSync(file)) {
    fs.writeFileSync(file, initTemplate(), "utf8");
    return { file, created: true };
  }
  return { file, created: false };
}

export function readManifest(file: string): { raw: string; data: Manifest } {
  const raw = fs.readFileSync(file, "utf8");
  const data = parse(raw) as Manifest;
  if (!data?.settings || !Array.isArray(data?.slices)) {
    throw new Error(`Invalid manifest shape: ${file}`);
  }
  return { raw, data };
}

export function writeManifest(file: string, raw: string) {
  fs.writeFileSync(file, raw, "utf8");
}

function slugId(name: string) {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function normChannel(channel: string) {
  return channel.trim().toLowerCase();
}

function relPosix(p: string) {
  const rel = path.relative(process.cwd(), path.resolve(p));
  return rel.split(path.sep).join("/");
}

export function addToSlice(args: {
  manifestFile: string;
  sliceName: string;
  channel: string;
  inputPaths: string[];
  kindOverride?: "file" | "dir";
}) {
  const { manifestFile, sliceName, channel, inputPaths } = args;

  const { raw, data } = readManifest(manifestFile);

  const id = slugId(sliceName);
  const chan = normChannel(channel);
  const paths = inputPaths.map(relPosix);

  let slice = data.slices.find((s) => s.id === id);

  // Create slice if missing
  let next = raw;
  if (!slice) {
    const newSlice: SliceDef = { id, name: sliceName, channel: chan, items: [] };
    const edits = modify(next, ["slices", data.slices.length], newSlice, { formattingOptions: FORMAT });
    next = applyEdits(next, edits);
    writeManifest(manifestFile, next);
  }

  // Re-read
  const { raw: raw2, data: data2 } = readManifest(manifestFile);
  slice = data2.slices.find((s) => s.id === id);
  if (!slice) throw new Error("Failed to create slice");

  // Update channel to latest provided (simple, predictable)
  if (slice.channel !== chan) {
    const idx = data2.slices.findIndex((s) => s.id === id);
    const edits = modify(raw2, ["slices", idx, "channel"], chan, { formattingOptions: FORMAT });
    next = applyEdits(raw2, edits);
    writeManifest(manifestFile, next);
  } else {
    next = raw2;
  }

  // Re-read again if we changed channel
  const { raw: raw3, data: data3 } = readManifest(manifestFile);
  const idx = data3.slices.findIndex((s) => s.id === id);
  const s3 = data3.slices[idx];

  const kind = args.kindOverride ?? "file";

  const existing = new Set(
    s3.items.filter((i) => i.kind === kind).map((i) => i.path)
  );

const toAdd = paths
  .filter((p) => !existing.has(p))
  .map((p) => ({ kind, path: p }));

  if (toAdd.length === 0) return { changed: false, added: 0 };

  let out = raw3;
  const base = s3.items.length;
  for (let i = 0; i < toAdd.length; i++) {
    const edits = modify(out, ["slices", idx, "items", base + i], toAdd[i], { formattingOptions: FORMAT });
    out = applyEdits(out, edits);
  }

  writeManifest(manifestFile, out);
  return { changed: true, added: toAdd.length };
}

export function removeFromSlice(args: { manifestFile: string; sliceName: string; inputPaths: string[] }) {
  const { manifestFile, sliceName, inputPaths } = args;
  const { raw, data } = readManifest(manifestFile);

  const id = slugId(sliceName);
  const idx = data.slices.findIndex((s) => s.id === id);
  if (idx === -1) return { changed: false, removed: 0 };

  const paths = new Set(inputPaths.map(relPosix));
  const before = data.slices[idx].items.length;
  const kept = data.slices[idx].items.filter((i) => !paths.has(i.path));
  const after = kept.length;

  if (after === before) return { changed: false, removed: 0 };

  const edits = modify(raw, ["slices", idx, "items"], kept, { formattingOptions: FORMAT });
  const next = applyEdits(raw, edits);
  writeManifest(manifestFile, next);

  return { changed: true, removed: before - after };
}