import fs from "node:fs";
import path from "node:path";
import { readManifest } from "./manifest.js";

const DIR_EXTS = new Set([
  ".ts", ".tsx", ".js", ".jsx",
  ".html", ".css", ".scss",
  ".json", ".jsonc",
  ".md", ".txt"
]);

function globLiteExts(patterns?: string[]): Set<string> | null {
  if (!patterns || patterns.length === 0) return null;

  const exts = new Set<string>();
  for (const p of patterns) {
    const m = p.match(/\*\*\/\*\.([a-z0-9]+)$/i);
    if (m) exts.add("." + m[1].toLowerCase());
  }
  return exts.size ? exts : null;
}

function matchesExclude(rel: string, patterns?: string[]): boolean {
  if (!patterns) return false;
  const name = rel.toLowerCase();

  return patterns.some((p) => {
    if (p.endsWith(".map")) return name.endsWith(".map");
    if (p.includes(".min.")) return name.includes(".min.");
    return false;
  });
}

function estimateTokensFromChars(charCount: number) {
  return Math.ceil(charCount / 4);
}

function lower(value?: string | null): string {
  return (value ?? "").trim().toLowerCase();
}

function getSliceGroup(slice: { group?: string | null; channel?: string | null }): string {
  return lower(slice.group ?? slice.channel ?? "default") || "default";
}

function collectDirFiles(
  dirRel: string,
  includeExts: Set<string> | null,
  exclude: string[]
): string[] {
  const out: string[] = [];
  const stack = [dirRel];

  while (stack.length) {
    const cur = stack.pop()!;
    const abs = path.isAbsolute(cur) ? cur : path.resolve(process.cwd(), cur);

    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(abs, { withFileTypes: true });
    } catch {
      continue;
    }

    for (const e of entries) {
      const base = cur.replaceAll("\\", "/");
      const rel = (base + "/" + e.name).replaceAll("//", "/");
      if (e.isDirectory()) {
        stack.push(rel);
      } else {
        const ext = path.extname(e.name).toLowerCase();

        if (includeExts && !includeExts.has(ext)) continue;
        if (!includeExts && !DIR_EXTS.has(ext)) continue;
        if (matchesExclude(rel, exclude)) continue;

        out.push(rel);
      }
    }
  }

  return out.sort();
}

export function buildCmd(manifestFile: string, target?: string) {
  const { data } = readManifest(manifestFile);

  const outFile = path.join(process.cwd(), data.settings?.contextFile ?? "slice_context.md");
  const missingFiles: string[] = [];

  const needle = target?.trim().toLowerCase();

  // If target provided but no group match, try slice id/name.
  // Support both `group` and legacy `channel` during migration.
  const chosen =
    !needle
      ? data.slices
      : data.slices.some((s) => getSliceGroup(s) === needle)
        ? data.slices.filter((s) => getSliceGroup(s) === needle)
        : data.slices.filter((s) => lower(s.id) === needle || lower(s.name) === needle);

  if (needle && chosen.length === 0) {
    throw new Error(`Nothing matched "${target}" (group or slice)`);
  }

  const ignore = data.settings?.ignore ?? [];
  const includeExts = globLiteExts(data.settings?.dirInclude);
  const exclude = data.settings?.dirExclude ?? [];

  const treeCfg = data.settings?.tree as
    | { roots?: string[]; maxDepth?: number; maxEntries?: number; mode?: "dirs-only" | "dirs-and-files" }
    | undefined;

  const includedFiles = Array.from(
    new Set(
      chosen.flatMap((s) => {
        const files = s.items
          .filter((i) => i.kind === "file")
          .map((i) => i.path);

        const dirs = s.items
          .filter((i) => i.kind === "dir")
          .flatMap((i) => collectDirFiles(i.path, includeExts, exclude));

        return [...files, ...dirs];
      })
    )
  ).sort((a, b) => a.localeCompare(b));

  type TreeNode = { [name: string]: TreeNode };

  function addPath(root: TreeNode, p: string) {
    const parts = p.split("/").filter(Boolean);
    let node = root;
    for (const part of parts) {
      node[part] ||= {};
      node = node[part];
    }
  }

  function renderTree(node: TreeNode, prefix = ""): string[] {
    const keys = Object.keys(node).sort((a, b) => a.localeCompare(b));
    const lines: string[] = [];
    keys.forEach((key, idx) => {
      const last = idx === keys.length - 1;
      const branch = last ? "└── " : "├── ";
      lines.push(prefix + branch + key);
      const child = node[key];
      const childKeys = Object.keys(child);
      if (childKeys.length > 0) {
        const nextPrefix = prefix + (last ? "    " : "│   ");
        lines.push(...renderTree(child, nextPrefix));
      }
    });
    return lines;
  }

  let md =
    `<!--\n` +
    `This file was generated by zzza.\n` +
    `The following is a context map of user selected files for AI-assisted work.\n` +
    `Treat missing files or warnings below as signals, rather than errors.\n` +
    `-->\n\n` +
    `# zzza Context\n\n`;
  md += needle ? `Built for: \`${target}\`\n\n` : `Built for: \`all\`\n\n`;

  md += `## Included files (${includedFiles.length})\n\n`;
  for (const f of includedFiles) {
    md += `- \`${f}\`\n`;
  }
  md += `\n`;

  const treeRoot: TreeNode = {};
  const treeMaxDepth = treeCfg?.maxDepth ?? 6;
  const treeMaxEntries = treeCfg?.maxEntries ?? 500;
  const treeMode = treeCfg?.mode ?? "dirs-and-files";

  const ignorePrefixes = ignore
    .map((r) => r.trim())
    .filter(Boolean)
    .map((r) => (r.endsWith("/**") ? r.slice(0, -3) : r))
    .filter((r) => !r.includes("*"));

  function isIgnored(rel: string) {
    const norm = rel.replaceAll("\\", "/");
    return ignorePrefixes.some((pfx) => norm === pfx || norm.startsWith(pfx + "/"));
  }

  let treeEntries = 0;

  function walkTree(rootRel: string, depth: number) {
    if (treeEntries >= treeMaxEntries) return;
    if (depth > treeMaxDepth) return;

    const absRoot = path.isAbsolute(rootRel) ? rootRel : path.resolve(process.cwd(), rootRel);
    let dirents: fs.Dirent[];
    try {
      dirents = fs.readdirSync(absRoot, { withFileTypes: true });
    } catch {
      addPath(treeRoot, rootRel.replaceAll("\\", "/"));
      treeEntries++;
      return;
    }

    dirents.sort((a, b) => a.name.localeCompare(b.name));

    for (const d of dirents) {
      if (treeEntries >= treeMaxEntries) return;

      const childRel = (rootRel.replaceAll("\\", "/") + "/" + d.name).replaceAll("//", "/");
      if (isIgnored(childRel)) continue;

      if (d.isDirectory()) {
        addPath(treeRoot, childRel);
        treeEntries++;
        walkTree(childRel, depth + 1);
      } else if (treeMode === "dirs-and-files") {
        addPath(treeRoot, childRel);
        treeEntries++;
      }
    }
  }

  const roots = (treeCfg?.roots ?? []).map((r) => r.trim()).filter(Boolean);

  if (roots.length > 0) {
    for (const r of roots) {
      if (isIgnored(r)) continue;
      addPath(treeRoot, r.replaceAll("\\", "/"));
      treeEntries++;
      walkTree(r, 1);
    }
  } else {
    for (const p of includedFiles) addPath(treeRoot, p);
  }

  md += `## Context Tree\n\n`;
  md += "```txt\n";
  md += ".\n";
  md += renderTree(treeRoot).join("\n") + "\n";
  md += "```\n\n";

  for (const s of chosen) {
    md += `## Slice: ${s.name} (${s.id})\n`;
    md += `group: \`${getSliceGroup(s)}\`\n\n`;

    const fileItems = s.items.filter((i) => i.kind === "file");
    const dirItems = s.items.filter((i) => i.kind === "dir");

    for (const d of dirItems) {
      md += `### Directory: \`${d.path}\`\n\n`;
      const expanded = collectDirFiles(d.path, includeExts, exclude);
      if (expanded.length === 0) {
        missingFiles.push(d.path);
        md += "_(missing, unreadable, or empty after filters)_\n\n";
      } else {
        md += `Expanded files (${expanded.length}):\n\n`;
        for (const f of expanded) md += `- \`${f}\`\n`;
        md += "\n";
      }
    }

    const allFiles = Array.from(
      new Set([
        ...fileItems.map((i) => i.path),
        ...dirItems.flatMap((i) => collectDirFiles(i.path, includeExts, exclude)),
      ])
    ).sort();

    for (const relPath of allFiles) {
      const abs = path.isAbsolute(relPath) ? relPath : path.resolve(process.cwd(), relPath);
      md += `### File: \`${relPath}\`\n\n`;
      try {
        const txt = fs.readFileSync(abs, "utf8");
        md += "```txt\n" + txt + "\n```\n\n";
      } catch {
        missingFiles.push(relPath);
        md += "_(missing or unreadable)_\n\n";
      }
    }
  }

  if (missingFiles.length > 0) {
    const warnList = missingFiles.map((p) => `• ${p}`).join("\n");
    const warnBlock =
      `> ⚠️ Build warning\n` +
      `>\n` +
      `> The following files were referenced in slice.jsonc\n` +
      `> but could not be read at build time:\n` +
      `>\n` +
      warnList.split("\n").map((line) => `> ${line}`).join("\n") +
      `\n\n`;
    md = warnBlock + md;
  }

  fs.writeFileSync(outFile, md, "utf8");

  const tw = data.settings?.tokenWarn;
  if (tw?.modelMaxTokens) {
    const warnAt = typeof tw.warnAt === "number" ? tw.warnAt : 0.85;
    const estimatedTokens = estimateTokensFromChars(md.length);
    const threshold = Math.floor(tw.modelMaxTokens * warnAt);

    if (estimatedTokens >= threshold) {
      console.log("");
      console.log("⚠️ Context size warning");
      console.log(`Estimated tokens: ~${estimatedTokens.toLocaleString()}`);
      console.log(
        `Configured max: ${tw.modelMaxTokens.toLocaleString()} (warnAt ${(warnAt * 100).toFixed(0)}%)`
      );
      console.log("");
      console.log("Tip: build a single slice/group, or tighten dirInclude/dirExclude.");
    }
  }

  console.log(`✓ Built ${path.relative(process.cwd(), outFile)}`);

  if (missingFiles.length > 0) {
    console.log("");
    console.log(`⚠️  ${missingFiles.length} file${missingFiles.length === 1 ? "" : "s"} could not be read:\n`);
    for (const p of missingFiles) {
      console.log(`  • ${p}`);
      console.log(`    (path not found or unreadable)`);
    }
    console.log("");
    console.log("Tip: Run `zzza doctor` to diagnose common issues.");
  }
}