import fs from "node:fs";
import path from "node:path";
import { parse, applyEdits, modify, FormattingOptions } from "jsonc-parser";

export type SliceItem = { kind: "file" | "dir"; path: string };
export type SliceDef = {
  id: string;
  name: string;
  group: string;
  items: SliceItem[];
};

export type Manifest = {
  settings: {
    contextFile: string;
    ignore: string[];
    dirInclude?: string[];
    dirExclude?: string[];
    tokenWarn?: {
      modelMaxTokens?: number;
      warnAt?: number; // 0..1 (e.g. 0.85)
    };
    tree?:
      | {
          roots?: string[];
          maxDepth?: number;
          maxEntries?: number;
          mode?: "dirs-only" | "dirs-and-files";
        }
      | undefined;
  };
  slices: SliceDef[];
};

export type AddToSliceResult = {
  changed: boolean;
  added: number;
  /** Preferred name */
  groupChanged: boolean;
  /** Back-compat alias */
  channelChanged: boolean;
};

const FORMAT: FormattingOptions = { insertSpaces: true, tabSize: 2, eol: "\n" };

export const DEFAULT_MANIFEST_FILE = "slice.jsonc";

export function manifestPath(cwd = process.cwd(), filename = DEFAULT_MANIFEST_FILE) {
  return path.join(cwd, filename);
}

export function initTemplate(): string {
  // Note: JSONC with comments. Keep it human-editable.
    return `{
  // Global settings for zzza.
  // This file is safe to edit by hand.
  // Comments and formatting will be preserved.
  "settings": {
    // The file generated by \`zzza build\`
    "contextFile": "slice_context.md",

    // Common generated / metadata paths are ignored by default.
    // Add paths or glob patterns zzza should ignore here
    "ignore": ["node_modules/**", "dist/**", ".git/**"],

    // File filters applied when expanding directories.
    // These are glob-lite (extension + substring based).
    "dirInclude": ["**/*.ts", "**/*.html", "**/*.css", "**/*.scss", "**/*.md"],
    "dirExclude": ["**/*.map", "**/*.min.*"],

    // Optional: token warning (estimate) for slice_context.md.
    // This is an approximation; actual truncation depends on your model/tool.
    "tokenWarn": { "modelMaxTokens": 128000, "warnAt": 0.85 },

    // Optional: generate a context tree from specific roots.
    // mode: "dirs-only" is more token-efficient than "dirs-and-files".
    // Example:
    // "tree": { "roots": ["src"], "mode": "dirs-only", "maxDepth": 6, "maxEntries": 500 }
    "tree": { "roots": [], "mode": "dirs-only", "maxDepth": 6, "maxEntries": 500 }
  },

  // Slices are named groups of files.
  // Each slice belongs to a "group" (a simple tag, often a color).
  "slices": []
}
`;
}

export function ensureManifest(cwd = process.cwd()): { file: string; created: boolean } {
  const file = manifestPath(cwd);
  if (!fs.existsSync(file)) {
    fs.writeFileSync(file, initTemplate(), "utf8");
    return { file, created: true };
  }
  return { file, created: false };
}

export function readManifest(file: string): { raw: string; data: Manifest } {
  const raw = fs.readFileSync(file, "utf8");
  const data = parse(raw) as Manifest;
  if (!data?.settings || !Array.isArray(data?.slices)) {
    throw new Error(`Invalid manifest shape: ${file}`);
  }
  return { raw, data };
}

export function writeManifest(file: string, raw: string) {
  fs.writeFileSync(file, raw, "utf8");
}

function slugId(name: string) {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function uniqueSliceId(base: string, slices: SliceDef[]) {
  let id = base;
  let n = 2;
  while (slices.some((s) => s.id === id)) {
    id = `${base}-${n}`;
    n++;
  }
  return id;
}

function normChannel(group: string) {
  return group.trim().toLowerCase();
}

function relPosix(p: string) {
  // Normalize and resolve to an absolute path.
  // If the path is outside the current cwd, keep it absolute to avoid ../../.. trees.
  const cleaned = (p ?? "")
    .toString()
    .replace(/\\/g, "/")
    .replace(/\/+$/g, "");

  const abs = path.resolve(cleaned || ".");
  const cwd = process.cwd();
  const rel = path.relative(cwd, abs);

  const isOutside = rel.startsWith("..") || path.isAbsolute(rel);
  const out = isOutside ? abs : rel;

  return out.split(path.sep).join("/").replace(/\/+$/g, "");
}

function samePath(a: string, b: string) {
  const na = a.replace(/\\/g, "/").replace(/\/+$/g, "");
  const nb = b.replace(/\\/g, "/").replace(/\/+$/g, "");
  return na === nb;
}

function normStoredPath(p: string) {
  return (p ?? "").toString().replace(/\\/g, "/").replace(/\/+$/g, "");
}

function sanitizeItems(items: SliceItem[]): { items: SliceItem[]; changed: boolean } {
  // Preserve first-seen order, de-dupe by normalized path.
  // If both file+dir exist for the same path, keep a single entry and prefer `dir`.
  const order: string[] = [];
  const byPath = new Map<string, SliceItem>();

  for (const it of items) {
    const p = normStoredPath(it.path);
    if (!p) continue;

    const existing = byPath.get(p);
    if (!existing) {
      order.push(p);
      byPath.set(p, { kind: it.kind, path: p });
      continue;
    }

    // Prefer dir over file.
    if (existing.kind === "file" && it.kind === "dir") {
      byPath.set(p, { kind: "dir", path: p });
    }
  }

  const cleaned = order.map((p) => byPath.get(p)!).filter(Boolean);

  const before = items.map((i) => `${i.kind}:${normStoredPath(i.path)}`).join("|");
  const after = cleaned.map((i) => `${i.kind}:${i.path}`).join("|");

  return { items: cleaned, changed: before !== after };
}

export function addToSlice(args: {
  manifestFile: string;
  sliceName: string;
  group?: string;
  inputPaths: string[];
  kindOverride?: "file" | "dir";
}): AddToSliceResult {
  const { manifestFile, sliceName, group, inputPaths } = args;
  let channelChanged = false;

  const { raw, data } = readManifest(manifestFile);

  const baseId = slugId(sliceName);
  const chan = normChannel(group ?? "default");
  const paths = inputPaths
    .map(relPosix)
    .map((p) => p.replace(/\/+$/g, ""))
    .filter((p) => p.length > 0);

  // Prefer exact name match to avoid slug collisions.
  let slice = data.slices.find((s) => s.name === sliceName) ?? data.slices.find((s) => s.id === baseId);

  // Create slice if missing
  let next = raw;
  if (!slice) {
    const id = uniqueSliceId(baseId, data.slices);
    const newSlice: SliceDef = { id, name: sliceName, group: chan, items: [] };
    const edits = modify(next, ["slices", data.slices.length], newSlice, { formattingOptions: FORMAT });
    next = applyEdits(next, edits);
    writeManifest(manifestFile, next);
  }

  // Re-read
  const { raw: raw2, data: data2 } = readManifest(manifestFile);
  slice = data2.slices.find((s) => s.name === sliceName) ?? data2.slices.find((s) => s.id === baseId);
  if (!slice) throw new Error("Failed to create slice");

  // Update group only if explicitly provided (keeps CLI add/remove symmetrical)
  if (typeof group === "string" && group.trim().length > 0 && slice.group !== chan) {
    const idx = data2.slices.findIndex((s) => s.id === slice.id);
    const edits = modify(raw2, ["slices", idx, "group"], chan, { formattingOptions: FORMAT });
    next = applyEdits(raw2, edits);
    writeManifest(manifestFile, next);
    channelChanged = true;
  } else {
    next = raw2;
  }

  // Re-read again if we changed group
  const { raw: raw3, data: data3 } = readManifest(manifestFile);
  const idx = data3.slices.findIndex((s) => s.id === slice.id);
  const s3 = data3.slices[idx];

  // Keep the manifest tidy: normalize paths, remove duplicates, and prefer `dir` over `file`.
  const sanitized = sanitizeItems(s3.items);
  if (sanitized.changed) {
    const edits = modify(raw3, ["slices", idx, "items"], sanitized.items, { formattingOptions: FORMAT });
    const nextRaw = applyEdits(raw3, edits);
    writeManifest(manifestFile, nextRaw);

    // Re-read to keep subsequent operations consistent.
    const reread = readManifest(manifestFile);
    const sIdx = reread.data.slices.findIndex((s) => s.id === slice.id);
    const sNow = reread.data.slices[sIdx];
    (s3 as any).items = sNow.items;
  }

  const kind = args.kindOverride ?? "file";

  // If caller is adding files, but a provided path is actually a directory,
  // promote it to a dir item to avoid storing the same path as both file+dir.
  const filePaths: string[] = [];
  const dirPaths: string[] = [];

  for (const p of paths) {
    const abs = path.isAbsolute(p) ? p : path.resolve(process.cwd(), p);
    try {
      const st = fs.lstatSync(abs);
      if (st.isDirectory()) dirPaths.push(p);
      else filePaths.push(p);
    } catch {
      // If it can't be stat'd, keep the caller intent.
      if (kind === "dir") dirPaths.push(p);
      else filePaths.push(p);
    }
  }

  // Promote directories when kind is "file".
  const addFiles = kind === "file" ? filePaths : [];
  const addDirs = kind === "dir" ? dirPaths : (kind === "file" ? dirPaths : []);

  // If we're adding dirs, prune any existing file items that have the same path.
  if (addDirs.length > 0) {
    const pruned = s3.items.filter((it) => !(it.kind === "file" && addDirs.some((p) => samePath(normStoredPath(it.path), normStoredPath(p)))));
    if (pruned.length !== s3.items.length) {
      const edits = modify(raw3, ["slices", idx, "items"], pruned, { formattingOptions: FORMAT });
      const nextItemsRaw = applyEdits(raw3, edits);
      writeManifest(manifestFile, nextItemsRaw);

      // Re-read so subsequent additions use the updated items list.
      const reread = readManifest(manifestFile);
      const sIdx = reread.data.slices.findIndex((s) => s.id === slice!.id);
      const sNow = reread.data.slices[sIdx];
      (s3 as any).items = sNow.items;
    }
  }

  const existingFiles = new Set(s3.items.filter((i) => i.kind === "file").map((i) => i.path.replace(/\/+$/g, "")));
  const existingDirs = new Set(s3.items.filter((i) => i.kind === "dir").map((i) => i.path.replace(/\/+$/g, "")));

  const fileAdds = addFiles
    .filter((p) => !existingFiles.has(p))
    .map((p) => ({ kind: "file" as const, path: p }));

  const dirAdds = addDirs
    .filter((p) => !existingDirs.has(p))
    .map((p) => ({ kind: "dir" as const, path: p }));

  const toAdd = [...fileAdds, ...dirAdds];

  if (toAdd.length === 0)
    return {
      changed: channelChanged,
      added: 0,
      groupChanged: channelChanged,
      channelChanged,
    };

  let out = raw3;
  const base = s3.items.length;
  for (let i = 0; i < toAdd.length; i++) {
    const edits = modify(out, ["slices", idx, "items", base + i], toAdd[i], { formattingOptions: FORMAT });
    out = applyEdits(out, edits);
  }

  writeManifest(manifestFile, out);
  return {
    changed: true,
    added: toAdd.length,
    groupChanged: channelChanged,
    channelChanged,
  };
}

export function removeFromSlice(args: { manifestFile: string; sliceName: string; inputPaths: string[] }) {
  const { manifestFile, sliceName, inputPaths } = args;
  const { raw, data } = readManifest(manifestFile);

  const id = slugId(sliceName);
  const idx = data.slices.findIndex((s) => s.id === id);
  if (idx === -1) return { changed: false, removed: 0 };

  const paths = new Set(inputPaths.map(relPosix).map(normStoredPath));
  const before = data.slices[idx].items.length;
  const kept = data.slices[idx].items.filter((i) => !paths.has(normStoredPath(i.path)));
  const after = kept.length;

  if (after === before) return { changed: false, removed: 0 };

  const edits = modify(raw, ["slices", idx, "items"], kept, { formattingOptions: FORMAT });
  const next = applyEdits(raw, edits);
  writeManifest(manifestFile, next);

  return { changed: true, removed: before - after };
}

export function removeSlice(args: { manifestFile: string; sliceName: string }) {
  const { manifestFile, sliceName } = args;
  const { raw, data } = readManifest(manifestFile);

  const id = slugId(sliceName);
  const idx = data.slices.findIndex((s) => s.name === sliceName || s.id === id);
  if (idx === -1) return { changed: false };

  const kept = data.slices.filter((_, i) => i !== idx);

  const edits = modify(raw, ["slices"], kept, { formattingOptions: FORMAT });
  const next = applyEdits(raw, edits);
  writeManifest(manifestFile, next);

  return { changed: true };
}