import fs from "node:fs";
import path from "node:path";
import { readManifest } from "./manifest.js";

export function buildCmd(manifestFile: string, target?: string) {
  const { data } = readManifest(manifestFile);

  const outFile = path.join(process.cwd(), data.settings?.contextFile ?? "slice_context.md");
  const missingFiles: string[] = [];

  const needle = target?.trim().toLowerCase();


  // If target provided but no channel match, try slice id/name
  const chosen =
    !needle
      ? data.slices
      : (data.slices.some((s) => s.channel.toLowerCase() === needle)
          ? data.slices.filter((s) => s.channel.toLowerCase() === needle)
          : data.slices.filter((s) => s.id.toLowerCase() === needle || s.name.toLowerCase() === needle));

  if (needle && chosen.length === 0) {
    throw new Error(`Nothing matched "${target}" (channel or slice)`);
  }

  const ignore = data.settings?.ignore ?? [];

  const treeCfg = data.settings?.tree as
  | { roots?: string[]; maxDepth?: number; maxEntries?: number; mode?: "dirs-only" | "dirs-and-files" }
  | undefined;

  // Precompute included file paths for an at-a-glance index/tree.
  const includedFiles = Array.from(
    new Set(
      chosen
        .flatMap((s) => s.items)
        .filter((i) => i.kind === "file")
        .map((i) => i.path)
    )
  ).sort((a, b) => a.localeCompare(b));

  type TreeNode = { [name: string]: TreeNode };

  function addPath(root: TreeNode, p: string) {
    const parts = p.split("/").filter(Boolean);
    let node = root;
    for (const part of parts) {
      node[part] ||= {};
      node = node[part];
    }
  }

  function renderTree(node: TreeNode, prefix = ""): string[] {
    const keys = Object.keys(node).sort((a, b) => a.localeCompare(b));
    const lines: string[] = [];
    keys.forEach((key, idx) => {
      const last = idx === keys.length - 1;
      const branch = last ? "└── " : "├── ";
      lines.push(prefix + branch + key);
      const child = node[key];
      const childKeys = Object.keys(child);
      if (childKeys.length > 0) {
        const nextPrefix = prefix + (last ? "    " : "│   ");
        lines.push(...renderTree(child, nextPrefix));
      }
    });
    return lines;
  }

  // v0: ignore supports simple prefix rules for tree rendering (and "/**" prefixes).
  // Full glob matching may be added later.

  let md =
    `<!--\n` +
    `This file was generated by Sliceza.\n` +
    `The following is a context map of user selected files for AI-assisted work.\n` +
    `Treat missing files or warnings below as signals, rather than errors.\n` +
    `-->\n\n` +
    `# Sliceza Context\n\n`;
  md += needle ? `Built for: \`${target}\`\n\n` : `Built for: \`all\`\n\n`;

  md += `## Included files (${includedFiles.length})\n\n`;
  for (const f of includedFiles) {
    md += `- \`${f}\`\n`;
  }
  md += `\n`;

  // Context Tree: either from user-configured roots (settings.tree.roots) or from included files (fallback).
  const treeRoot: TreeNode = {};
  const treeMaxDepth = treeCfg?.maxDepth ?? 6;
  const treeMaxEntries = treeCfg?.maxEntries ?? 500;
  const treeMode = treeCfg?.mode ?? "dirs-and-files";

  // v0 ignore: support simple prefix ignores (and ignore entries ending with "/**" as prefixes). Globs still not supported.
  const ignorePrefixes = ignore
    .map((r) => r.trim())
    .filter(Boolean)
    .map((r) => (r.endsWith("/**") ? r.slice(0, -3) : r))
    .filter((r) => !r.includes("*"));

  function isIgnored(rel: string) {
    const norm = rel.replaceAll("\\", "/");
    return ignorePrefixes.some((pfx) => norm === pfx || norm.startsWith(pfx + "/"));
  }

  let treeEntries = 0;

  function walkTree(rootRel: string, depth: number) {
    if (treeEntries >= treeMaxEntries) return;
    if (depth > treeMaxDepth) return;

    const absRoot = path.resolve(process.cwd(), rootRel);
    let dirents: fs.Dirent[];
    try {
      dirents = fs.readdirSync(absRoot, { withFileTypes: true });
    } catch {
      // If a root can't be read, just show the root node (still useful) and stop.
      addPath(treeRoot, rootRel.replaceAll("\\", "/"));
      treeEntries++;
      return;
    }

    // Sort for stable output (dirs + files together is fine for v0)
    dirents.sort((a, b) => a.name.localeCompare(b.name));

        for (const d of dirents) {
      if (treeEntries >= treeMaxEntries) return;

      const childRel = (rootRel.replaceAll("\\", "/") + "/" + d.name).replaceAll("//", "/");
      if (isIgnored(childRel)) continue;

      if (d.isDirectory()) {
        // Always include directories (both modes)
        addPath(treeRoot, childRel);
        treeEntries++;
        walkTree(childRel, depth + 1);
      } else {
        // Only include files when mode allows it
        if (treeMode === "dirs-and-files") {
          addPath(treeRoot, childRel);
          treeEntries++;
        }
      }
    }
  }

  const roots = (treeCfg?.roots ?? []).map((r) => r.trim()).filter(Boolean);

  if (roots.length > 0) {
    for (const r of roots) {
      if (isIgnored(r)) continue;
      addPath(treeRoot, r.replaceAll("\\", "/"));
      treeEntries++;
      walkTree(r, 1);
    }
  } else {
    // Fallback: build tree from included files only.
    for (const p of includedFiles) addPath(treeRoot, p);
  }

  md += `## Context Tree\n\n`;
  md += "```txt\n";
  md += ".\n";
  md += renderTree(treeRoot).join("\n") + "\n";
  md += "```\n\n";

  for (const s of chosen) {
    md += `## Slice: ${s.name} (${s.id})\n`;
    md += `Channel: \`${s.channel}\`\n\n`;
    const fileItems = s.items.filter((i) => i.kind === "file");
    for (const it of fileItems) {
      const abs = path.resolve(process.cwd(), it.path);
      md += `### File: \`${it.path}\`\n\n`;
      try {
        const txt = fs.readFileSync(abs, "utf8");
        md += "```txt\n" + txt + "\n```\n\n";
      } catch {
        missingFiles.push(it.path);
        md += "_(missing or unreadable)_\n\n";
      }
    }
  }

  if (missingFiles.length > 0) {
    const warnList = missingFiles.map((p) => `• ${p}`).join("\n");
    const warnBlock =
      `> ⚠️ Build warning\n` +
      `>\n` +
      `> The following files were referenced in slice.jsonc\n` +
      `> but could not be read at build time:\n` +
      `>\n` +
      warnList.split("\n").map((line) => `> ${line}`).join("\n") +
      `\n\n`;
    md = warnBlock + md;
  }

  fs.writeFileSync(outFile, md, "utf8");
  console.log(`✓ Built ${path.relative(process.cwd(), outFile)}`);
  if (missingFiles.length > 0) {
    console.log("");
    console.log(`⚠️  ${missingFiles.length} file${missingFiles.length === 1 ? "" : "s"} could not be read:\n`);
    for (const p of missingFiles) {
      console.log(`  • ${p}`);
      console.log(`    (path not found or unreadable)`);
    }
    console.log("");
    console.log("Tip: Run `sliceza doctor` to diagnose common issues.");
  }
}